### PR TITLE
Fix unsound cppgc APIs

### LINKED ISSUE #1801: cppgc: Member and WeakMember must be unsafe
I could totally be missing something, but I've been digging for clues for a few hours, and it seems like almost all methods on `v8::cppgc::Member` and `v8::cppgc::WeakMember` have to be `unsafe`.

As far as I can discern, the invariants imposed by the V8 GC (including Oilpan) are:

1. `Member` pointers are valid if (and only if) they exist as members of an object implementing `GarbageCollected`, and that object accurately calls `trace()` for that member. Conversely, if an implementor of `GarbageCollected` does not visit the member, or if the `Member` pointer has not been visited between its initialization and the last GC pass for some other reason, accessing its contents is UB - the target object may have been dropped, or even moved (theoretically).
2. The same goes for `WeakMember`, which is eagerly changed to `NULL` internally by the tracer, so it can become dangling if it is missed during trace.

Furthermore, the `Member::new()` and `WeakMember::new()` force initialized pointers to exist on the stack, at least temporarily, even though that seems specifically dangerous. Perhaps the guidance should be to always create them using `empty()` etc. and explicitly call `set()` etc. when they have been placed on the heap using `make_cppgc_object()`.

### PR DESCRIPTION
**Pull request by simonask**
Fixes #1801 

This does a couple of things:

- The `GarbageCollected` trait is now an `unsafe trait`, because implementing it incorrectly can create dangling pointers.
- The `Member::borrow()` and `WeakMember::borrow()` methods are renamed to `get()`, because they do not return a borrow guard (i.e., they do not work like `RefCell`, nor do they work like the `Borrow` trait).
- `Member::get()` and `WeakMember::get()` are now also `unsafe`, because the caller must guarantee that the pointers are reachable by the GC before calling them.
- The `GarbageCollected` trait now implies `Send + Sync`, because the cppgc garbage collector considers itself free to both mark and sweep on other threads depending on configuration.
- And I updated a couple of doc comments.

### CODE REVIEW

File: src/cppgc.rs [hunk 1]
```diff
@@ -479,16 +493,22 @@ macro_rules! member {
           self.inner.assign(ptr);
         }
 
-        #[doc = "Borrow the object pointed to by this "]
+        #[doc = "Get the object pointed to by this "]
         #[doc = stringify!($name)]
-        #[doc = "."]
-        pub fn borrow(&self) -> Option<&T> {
+        #[doc = ", returning `None` if the pointer is empty or has been garbage-collected."]
+        #[doc = ""]
```
Comment (devsnek) [inline src/cppgc.rs:499]: are these newlines? i think they're just concatted. maybe just use a multiline string.

File: src/cppgc.rs [hunk 2]
```diff
@@ -324,12 +324,26 @@ impl Heap {
...
+/// Base trait for objects supporting garbage collection.
+///
+/// Objects implementing this trait must also implement `Send + Sync` because
+/// the garbage collector may perform concurrent mark/sweep phases (depending on
+/// the cppgc heap settings). In particular, the object's `drop()` method may be
+/// invoked from a different thread than the one that created the object.
+///
+/// # Safety
+///
+/// This trait is unsafe because implementors must guarantee that the `trace()`
```
Comment (devsnek) [inline src/cppgc.rs:336]:
```suggestion
/// implementors must guarantee that the `trace()`
```

File: src/cppgc.rs (hunk 1 above)
Comment (simonask) [reply src/cppgc.rs:499]: Yes, they are newlines. Doc attributes are interpreted the same way as lines in doc comments, so this is the usual approach to formatting them in macros, but I'm fine with whatever you think is best.

**Review by devsnek — APPROVED** [review]
